<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8hsiqNG\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8hsiqNG/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container8hsiqNG.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\Container8hsiqNG\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \Container8hsiqNG\srcDevDebugProjectContainer(array(
    'container.build_hash' => '8hsiqNG',
    'container.build_id' => '432de22f',
    'container.build_time' => 1547003076,
), __DIR__.\DIRECTORY_SEPARATOR.'Container8hsiqNG');
